language: rust
cache: cargo
dist: focal

# runs on both linux & windows, syntax must be compatible for both
script: |
  cargo build &&
  cargo test &&
  cargo doc --no-deps

# this matrix generates jos for the `test` stage
os:
  - linux
  - windows
rust:
  - nightly
  - beta
  - stable
  - 1.35.0

# run only one job first to see if it fails, then run the rest
jobs:
  include:
    - stage: fast-test
      os: linux
      rust: stable
  exclude:
    - stage: test
      os: linux
      rust: stable

stages:
  - fast-test
  - test
